### ISSUE TITLE
Refreshing droplets causes force close

### ISSUE THREAD

**Issue by KatsumeBlisk** [yassirh/digital-ocean-swimmer#32]
When I refresh my droplets, it causes the app to FC. I haven't seen it FC in any other case.

**Comment by yassirh** [comment]
Could you try again and report it when it crashes? so i can see the logs and determine the problem.

**Comment by KatsumeBlisk** [comment]
I sent two. I accidentally forgot to describe the first one. Did you get it? I've never used the report button before.

**Comment by yassirh** [comment]
I got it. so here is the stack trace I am getting : 

```
android.app.RemoteServiceException: Bad notification posted from package com.yassirh.digitalocean: Couldn't create icon: StatusBarIcon(pkg=com.yassirh.digitaloceanuser=0 id=0x7f020049 level=0 visible=true num=0 )
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1372)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
```
I don't know how i can reproduce it at the moment but I am investigating it. Meanwhile could you try reinstalling the app and trying again?

**Comment by KatsumeBlisk** [comment]
It still occurs after reinstalling. As soon as I log in, it crashes.

**Comment by yassirh** [comment]
I see. can you try the newest version : https://yassirh.com/digitalocean_swimmer/releases/DigitalOceanSwimmer-release-2.1.0.apk

**Comment by KatsumeBlisk** [comment]
That causes force closes as well.
